# Generated by Django 5.2.4 on 2025-07-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
    ]
